-- 審美者 MVP schema（兼容既有 videos 表版本）
-- 目標：保留舊 videos 表的既有資料，再補上 video + post 雙核心所需的新表與欄位。
-- 注意：這份 SQL 先作為可審閱 migration，不會自動執行到遠端 Supabase。

create extension if not exists "pgcrypto";

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function public.generate_numeric_username()
returns text
language plpgsql
as $$
declare
  candidate text;
begin
  loop
    candidate := floor(10000000 + random() * 90000000)::bigint::text;
    exit when not exists (
      select 1
      from public.profiles
      where username = candidate
    );
  end loop;

  return candidate;
end;
$$;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text not null unique,
  display_name text not null default '策展人',
  avatar_url text,
  bio text,
  aesthetic_tags text[] not null default '{}',
  message_permission text not null default 'followers',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint profiles_username_format check (username ~ '^[a-zA-Z0-9_]{3,32}$'),
  constraint profiles_message_permission_check check (
    message_permission in ('everyone', 'followers', 'none')
  )
);

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, username, display_name)
  values (
    new.id,
    public.generate_numeric_username(),
    coalesce(
      nullif(new.raw_user_meta_data ->> 'display_name', ''),
      split_part(new.email, '@', 1),
      '策展人'
    )
  )
  on conflict (id) do nothing;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

-- 舊專案已存在 public.videos，且已有資料：
-- id / bvid / title / cover / up_name / up_mid / duration / play_count / fav_time / added_by / status / curator_id
-- 所以這裡只在表不存在時建立舊兼容結構；若表已存在，下面會用 alter table 補新欄位。
create table if not exists public.videos (
  id bigint generated by default as identity primary key,
  bvid text,
  title text not null,
  cover text,
  up_name text,
  up_mid bigint,
  duration integer,
  play_count integer,
  fav_time bigint,
  added_by text,
  status text,
  curator_id uuid,
  created_at timestamptz not null default now()
);

alter table public.videos add column if not exists source_platform text;
alter table public.videos add column if not exists external_id text;
alter table public.videos add column if not exists source_url text;
alter table public.videos add column if not exists cover_url text;
alter table public.videos add column if not exists author_name text;
alter table public.videos add column if not exists duration_seconds integer;
alter table public.videos add column if not exists metadata jsonb not null default '{}'::jsonb;
alter table public.videos add column if not exists updated_at timestamptz not null default now();

-- 將舊欄位映射到新欄位。這一步不刪舊欄位，確保現有首頁仍能工作。
update public.videos
set
  source_platform = coalesce(source_platform, 'bilibili'),
  external_id = coalesce(external_id, bvid),
  source_url = coalesce(source_url, case when bvid is not null then 'https://www.bilibili.com/video/' || bvid else null end),
  cover_url = coalesce(cover_url, cover),
  author_name = coalesce(author_name, up_name),
  duration_seconds = coalesce(duration_seconds, duration),
  metadata = case
    when metadata = '{}'::jsonb then jsonb_build_object(
      'legacy_id', id,
      'up_mid', up_mid,
      'play_count', play_count,
      'fav_time', fav_time,
      'added_by', added_by,
      'legacy_status', status,
      'curator_id', curator_id
    )
    else metadata
  end;

alter table public.videos alter column source_platform set default 'bilibili';
alter table public.videos alter column source_platform set not null;
alter table public.videos alter column external_id set not null;
alter table public.videos alter column source_url set not null;

drop trigger if exists videos_set_updated_at on public.videos;
create trigger videos_set_updated_at
before update on public.videos
for each row execute function public.set_updated_at();

create unique index if not exists videos_source_external_unique_idx
on public.videos (source_platform, external_id);

create table if not exists public.posts (
  id uuid primary key default gen_random_uuid(),
  -- 舊 videos 資料目前只有 added_by 文字，未必能對應 auth.users。
  -- 因此 user_id 允許暫時為 null，legacy_added_by 用來保留舊資料來源。
  user_id uuid references public.profiles(id) on delete set null,
  legacy_added_by text,
  video_id bigint not null references public.videos(id) on delete cascade,
  note text not null,
  visibility text not null default 'public',
  status text not null default 'published',
  like_count integer not null default 0,
  comment_count integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint posts_author_present check (user_id is not null or legacy_added_by is not null),
  constraint posts_note_min_length check (char_length(trim(note)) >= 10),
  constraint posts_visibility_check check (visibility in ('public', 'followers', 'private')),
  constraint posts_status_check check (status in ('draft', 'published', 'hidden', 'deleted')),
  constraint posts_like_count_non_negative check (like_count >= 0),
  constraint posts_comment_count_non_negative check (comment_count >= 0)
);

drop trigger if exists posts_set_updated_at on public.posts;
create trigger posts_set_updated_at
before update on public.posts
for each row execute function public.set_updated_at();

-- 將既有 videos 舊資料轉成 legacy posts。
-- 這樣未來首頁從 videos 切到 posts 時，舊 20 條內容不會消失。
-- 舊資料目前沒有 auth user 可關聯，所以先使用 legacy_added_by 保留來源。
insert into public.posts (
  video_id,
  legacy_added_by,
  note,
  visibility,
  status,
  created_at,
  updated_at
)
select
  videos.id,
  coalesce(nullif(videos.added_by, ''), 'legacy'),
  case
    when char_length(trim(coalesce(videos.title, ''))) >= 10 then videos.title
    else '舊影片資料，推薦理由待補。'
  end,
  'public',
  'published',
  coalesce(videos.created_at, now()),
  now()
from public.videos
where not exists (
  select 1
  from public.posts
  where posts.video_id = videos.id
    and posts.legacy_added_by = coalesce(nullif(videos.added_by, ''), 'legacy')
);

create table if not exists public.modules (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  name text not null,
  description text,
  cover_url text,
  theme_color text,
  owner_id uuid references public.profiles(id) on delete set null,
  status text not null default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint modules_slug_format check (slug ~ '^[a-z0-9-]{2,64}$'),
  constraint modules_status_check check (status in ('active', 'hidden', 'archived'))
);

drop trigger if exists modules_set_updated_at on public.modules;
create trigger modules_set_updated_at
before update on public.modules
for each row execute function public.set_updated_at();

create table if not exists public.post_modules (
  post_id uuid not null references public.posts(id) on delete cascade,
  module_id uuid not null references public.modules(id) on delete cascade,
  added_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),

  primary key (post_id, module_id)
);

create table if not exists public.comments (
  id uuid primary key default gen_random_uuid(),
  target_type text not null,
  post_id uuid references public.posts(id) on delete cascade,
  video_id bigint references public.videos(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  parent_id uuid references public.comments(id) on delete cascade,
  content text not null,
  status text not null default 'published',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint comments_target_type_check check (target_type in ('post', 'video')),
  constraint comments_target_match check (
    (target_type = 'post' and post_id is not null and video_id is null)
    or
    (target_type = 'video' and video_id is not null and post_id is null)
  ),
  constraint comments_content_not_empty check (char_length(trim(content)) > 0),
  constraint comments_status_check check (status in ('published', 'hidden', 'deleted'))
);

drop trigger if exists comments_set_updated_at on public.comments;
create trigger comments_set_updated_at
before update on public.comments
for each row execute function public.set_updated_at();

create table if not exists public.reactions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  target_type text not null,
  target_id uuid not null,
  reaction_type text not null default 'like',
  created_at timestamptz not null default now(),

  constraint reactions_target_type_check check (target_type in ('post')),
  constraint reactions_type_check check (reaction_type in ('like')),
  constraint reactions_unique unique (user_id, target_type, target_id, reaction_type)
);

create index if not exists profiles_username_idx on public.profiles (username);
create index if not exists videos_external_idx on public.videos (source_platform, external_id);
create index if not exists posts_feed_idx on public.posts (status, visibility, created_at desc);
create index if not exists posts_user_idx on public.posts (user_id, created_at desc);
create index if not exists posts_video_idx on public.posts (video_id, created_at desc);
create index if not exists modules_slug_idx on public.modules (slug);
create index if not exists post_modules_module_idx on public.post_modules (module_id);
create index if not exists comments_post_idx on public.comments (post_id, created_at desc);
create index if not exists comments_video_idx on public.comments (video_id, created_at desc);
create index if not exists reactions_target_idx on public.reactions (target_type, target_id);

create or replace function public.update_post_like_count()
returns trigger
language plpgsql
as $$
begin
  if tg_op = 'INSERT' and new.target_type = 'post' and new.reaction_type = 'like' then
    update public.posts
    set like_count = like_count + 1
    where id = new.target_id;
    return new;
  end if;

  if tg_op = 'DELETE' and old.target_type = 'post' and old.reaction_type = 'like' then
    update public.posts
    set like_count = greatest(like_count - 1, 0)
    where id = old.target_id;
    return old;
  end if;

  return null;
end;
$$;

drop trigger if exists reactions_update_post_like_count on public.reactions;
create trigger reactions_update_post_like_count
after insert or delete on public.reactions
for each row execute function public.update_post_like_count();

create or replace function public.update_post_comment_count()
returns trigger
language plpgsql
as $$
begin
  if tg_op = 'INSERT' and new.target_type = 'post' and new.status = 'published' then
    update public.posts
    set comment_count = comment_count + 1
    where id = new.post_id;
    return new;
  end if;

  if tg_op = 'DELETE' and old.target_type = 'post' and old.status = 'published' then
    update public.posts
    set comment_count = greatest(comment_count - 1, 0)
    where id = old.post_id;
    return old;
  end if;

  return coalesce(new, old);
end;
$$;

drop trigger if exists comments_update_post_comment_count on public.comments;
create trigger comments_update_post_comment_count
after insert or delete on public.comments
for each row execute function public.update_post_comment_count();

alter table public.profiles enable row level security;
alter table public.videos enable row level security;
alter table public.posts enable row level security;
alter table public.modules enable row level security;
alter table public.post_modules enable row level security;
alter table public.comments enable row level security;
alter table public.reactions enable row level security;

drop policy if exists "profiles are publicly readable" on public.profiles;
create policy "profiles are publicly readable"
on public.profiles for select
using (true);

drop policy if exists "users can update own profile" on public.profiles;
create policy "users can update own profile"
on public.profiles for update
using (auth.uid() = id)
with check (auth.uid() = id);

drop policy if exists "videos are publicly readable" on public.videos;
create policy "videos are publicly readable"
on public.videos for select
using (true);

drop policy if exists "authenticated users can insert videos" on public.videos;
create policy "authenticated users can insert videos"
on public.videos for insert
with check (auth.role() = 'authenticated');

drop policy if exists "published public posts are readable" on public.posts;
create policy "published public posts are readable"
on public.posts for select
using (status = 'published' and visibility = 'public');

drop policy if exists "authenticated users can insert own posts" on public.posts;
create policy "authenticated users can insert own posts"
on public.posts for insert
with check (auth.uid() = user_id);

drop policy if exists "users can update own posts" on public.posts;
create policy "users can update own posts"
on public.posts for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "users can delete own posts" on public.posts;
create policy "users can delete own posts"
on public.posts for delete
using (auth.uid() = user_id);

drop policy if exists "active modules are publicly readable" on public.modules;
create policy "active modules are publicly readable"
on public.modules for select
using (status = 'active');

drop policy if exists "post modules are readable for public posts" on public.post_modules;
create policy "post modules are readable for public posts"
on public.post_modules for select
using (
  exists (
    select 1
    from public.posts
    where posts.id = post_modules.post_id
      and posts.status = 'published'
      and posts.visibility = 'public'
  )
);

drop policy if exists "users can attach modules to own posts" on public.post_modules;
create policy "users can attach modules to own posts"
on public.post_modules for insert
with check (
  auth.uid() = added_by
  and exists (
    select 1
    from public.posts
    where posts.id = post_modules.post_id
      and posts.user_id = auth.uid()
  )
);

drop policy if exists "published comments are publicly readable" on public.comments;
create policy "published comments are publicly readable"
on public.comments for select
using (status = 'published');

drop policy if exists "authenticated users can insert own comments" on public.comments;
create policy "authenticated users can insert own comments"
on public.comments for insert
with check (auth.uid() = user_id);

drop policy if exists "users can update own comments" on public.comments;
create policy "users can update own comments"
on public.comments for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "users can delete own comments" on public.comments;
create policy "users can delete own comments"
on public.comments for delete
using (auth.uid() = user_id);

drop policy if exists "authenticated users can read reactions" on public.reactions;
create policy "authenticated users can read reactions"
on public.reactions for select
using (auth.role() = 'authenticated');

drop policy if exists "authenticated users can insert own reactions" on public.reactions;
create policy "authenticated users can insert own reactions"
on public.reactions for insert
with check (auth.uid() = user_id);

drop policy if exists "users can delete own reactions" on public.reactions;
create policy "users can delete own reactions"
on public.reactions for delete
using (auth.uid() = user_id);
