-- 審美者第一版可解釋推薦地基。
-- 使用者主動設定頻道偏好；曝光記錄只用於短期去重，不記錄停留時長。

create table if not exists public.user_channel_preferences (
  user_id uuid not null references public.profiles(id) on delete cascade,
  module_id uuid not null references public.modules(id) on delete cascade,
  preference smallint not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  primary key (user_id, module_id),
  constraint user_channel_preferences_range check (preference between -2 and 2)
);

comment on table public.user_channel_preferences
  is '使用者主動調整的頻道推薦強度；-2 不推薦、-1 少一點、0 正常、1/2 多一點';

drop trigger if exists user_channel_preferences_set_updated_at on public.user_channel_preferences;
create trigger user_channel_preferences_set_updated_at
before update on public.user_channel_preferences
for each row execute function public.set_updated_at();

create table if not exists public.feed_impressions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  session_id text not null,
  post_id uuid not null references public.posts(id) on delete cascade,
  reason_code text not null default 'explore',
  shown_at timestamptz not null default now(),

  constraint feed_impressions_reason_check check (
    reason_code in ('channel_preference', 'following', 'fresh', 'discussion', 'explore')
  ),
  constraint feed_impressions_session_post_unique unique (user_id, session_id, post_id)
);

comment on table public.feed_impressions
  is '推薦批次曝光記錄，只用於近期去重與推薦原因檢查，不記錄停留時長';

create index if not exists user_channel_preferences_user_idx
  on public.user_channel_preferences (user_id, preference desc);

create index if not exists feed_impressions_user_recent_idx
  on public.feed_impressions (user_id, shown_at desc);

create index if not exists feed_impressions_post_idx
  on public.feed_impressions (post_id, shown_at desc);

alter table public.user_channel_preferences enable row level security;
alter table public.feed_impressions enable row level security;

drop policy if exists "users can read own channel preferences" on public.user_channel_preferences;
create policy "users can read own channel preferences"
on public.user_channel_preferences for select
using (auth.uid() = user_id);

drop policy if exists "users can create own channel preferences" on public.user_channel_preferences;
create policy "users can create own channel preferences"
on public.user_channel_preferences for insert
with check (auth.uid() = user_id);

drop policy if exists "users can update own channel preferences" on public.user_channel_preferences;
create policy "users can update own channel preferences"
on public.user_channel_preferences for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "users can delete own channel preferences" on public.user_channel_preferences;
create policy "users can delete own channel preferences"
on public.user_channel_preferences for delete
using (auth.uid() = user_id);

drop policy if exists "users can read own feed impressions" on public.feed_impressions;
create policy "users can read own feed impressions"
on public.feed_impressions for select
using (auth.uid() = user_id);

drop policy if exists "users can create own feed impressions" on public.feed_impressions;
create policy "users can create own feed impressions"
on public.feed_impressions for insert
with check (auth.uid() = user_id);
